-- MySQL Script generated by MySQL Workbench
-- 08/12/15 00:21:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SAD360
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SAD360` ;

-- -----------------------------------------------------
-- Schema SAD360
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAD360` DEFAULT CHARACTER SET utf8 ;
USE `SAD360` ;

-- -----------------------------------------------------
-- Table `SAD360`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`questions` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`questions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `enunciation` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`alternatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`alternatives` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`alternatives` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`questionnaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`questionnaires` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`questionnaires` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `details` MEDIUMTEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`evaluations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`evaluations` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`evaluations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `details` MEDIUMTEXT NOT NULL COMMENT '',
  `questionnaire_id` INT UNSIGNED NOT NULL COMMENT '',
  `start` DATE NOT NULL COMMENT '',
  `end` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_avaliacoes_questionarios1_idx` (`questionnaire_id` ASC)  COMMENT '',
  CONSTRAINT `fk_avaliacoes_questionarios1`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `SAD360`.`questionnaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`departments` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`departments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`users` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(50) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `role` VARCHAR(20) NOT NULL COMMENT '',
  `name` VARCHAR(250) NOT NULL COMMENT '',
  `cpf` VARCHAR(15) NOT NULL COMMENT '',
  `email` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `department_id` INT UNSIGNED NOT NULL COMMENT '',
  `image_path` VARCHAR(255) NULL COMMENT '',
  `user_id` INT UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_users_departamentos1_idx` (`department_id` ASC)  COMMENT '',
  INDEX `fk_users_users1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_departamentos1`
    FOREIGN KEY (`department_id`)
    REFERENCES `SAD360`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SAD360`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`alternatives_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`alternatives_questions` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`alternatives_questions` (
  `question_id` INT UNSIGNED NOT NULL COMMENT '',
  `alternative_id` INT UNSIGNED NOT NULL COMMENT '',
  `alternative_order` INT NOT NULL COMMENT '',
  PRIMARY KEY (`question_id`, `alternative_id`)  COMMENT '',
  INDEX `fk_questions_has_alternatives_alternatives1_idx` (`alternative_id` ASC)  COMMENT '',
  INDEX `fk_questions_has_alternatives_questions1_idx` (`question_id` ASC)  COMMENT '',
  CONSTRAINT `fk_questions_has_alternatives_questions1`
    FOREIGN KEY (`question_id`)
    REFERENCES `SAD360`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_has_alternatives_alternatives1`
    FOREIGN KEY (`alternative_id`)
    REFERENCES `SAD360`.`alternatives` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`evaluations_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`evaluations_users` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`evaluations_users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `evaluation_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_users_has_evaluations_evaluations1_idx` (`evaluation_id` ASC)  COMMENT '',
  INDEX `fk_users_has_evaluations_users1_idx` (`user_id` ASC)  COMMENT '',
  UNIQUE INDEX `user_evaluation_unq` (`user_id` ASC, `evaluation_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_has_evaluations_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SAD360`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_evaluations_evaluations1`
    FOREIGN KEY (`evaluation_id`)
    REFERENCES `SAD360`.`evaluations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`answers` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`answers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `evaluation_user_id` INT UNSIGNED NOT NULL COMMENT '',
  `question_id` INT UNSIGNED NOT NULL COMMENT '',
  `alternative_id` INT UNSIGNED NOT NULL COMMENT '',
  `users_id` INT UNSIGNED NOT NULL COMMENT '',
  `answered_in` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_alternatives_has_answers_idx` (`alternative_id` ASC)  COMMENT '',
  INDEX `fk_questions_has_answers_idx` (`question_id` ASC)  COMMENT '',
  UNIQUE INDEX `fk_answers_unq` (`question_id` ASC, `evaluation_user_id` ASC)  COMMENT '',
  INDEX `fk_answers_user_evaluations1_idx` (`evaluation_user_id` ASC)  COMMENT '',
  INDEX `fk_answers_users1_idx` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_alternatives_has_answers`
    FOREIGN KEY (`alternative_id`)
    REFERENCES `SAD360`.`alternatives` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_has_answers`
    FOREIGN KEY (`question_id`)
    REFERENCES `SAD360`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_user_evaluations1`
    FOREIGN KEY (`evaluation_user_id`)
    REFERENCES `SAD360`.`evaluations_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `SAD360`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAD360`.`questionnaires_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAD360`.`questionnaires_questions` ;

CREATE TABLE IF NOT EXISTS `SAD360`.`questionnaires_questions` (
  `questionnaire_id` INT UNSIGNED NOT NULL COMMENT '',
  `question_id` INT UNSIGNED NOT NULL COMMENT '',
  `question_number` INT NOT NULL COMMENT '',
  PRIMARY KEY (`questionnaire_id`, `question_id`)  COMMENT '',
  INDEX `fk_questionnaires_has_questions_questions1_idx` (`question_id` ASC)  COMMENT '',
  INDEX `fk_questionnaires_has_questions_questionnaires1_idx` (`questionnaire_id` ASC)  COMMENT '',
  CONSTRAINT `fk_questionnaires_has_questions_questionnaires1`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `SAD360`.`questionnaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionnaires_has_questions_questions1`
    FOREIGN KEY (`question_id`)
    REFERENCES `SAD360`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SAD360`.`departments`
-- -----------------------------------------------------
START TRANSACTION;
USE `SAD360`;
INSERT INTO `SAD360`.`departments` (`id`, `name`) VALUES (DEFAULT, 'Administrativo');
INSERT INTO `SAD360`.`departments` (`id`, `name`) VALUES (DEFAULT, 'Diretoria');
INSERT INTO `SAD360`.`departments` (`id`, `name`) VALUES (DEFAULT, 'Financeiro');
INSERT INTO `SAD360`.`departments` (`id`, `name`) VALUES (DEFAULT, 'Gerência');
INSERT INTO `SAD360`.`departments` (`id`, `name`) VALUES (DEFAULT, 'RH');

COMMIT;

